!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 32
  - - buffer_size
    - 40000
  - - ent_coef
    - auto_0.1_0.05
  - - env_wrapper
    - - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
          camera_noise_mean: 0
          camera_noise_stddev: 0.001
          camera_pose_rollouts_num: 1
          ground_model_rollouts_num: 1
          object_models_rollouts_num: 1
          object_random_model_count: 4
          object_random_pose: true
          object_random_use_mesh_models: true
          robot_random_joint_positions: true
          robot_random_joint_positions_std: 0.1
  - - gamma
    - 0.999
  - - gradient_steps
    - 100
  - - learning_rate
    - lin_0.00015
  - - learning_starts
    - 0
  - - n_timesteps
    - 500000
  - - noise_std
    - 0.025
  - - noise_type
    - normal
  - - optimize_memory_usage
    - true
  - - policy
    - OctreeCnnPolicy
  - - policy_kwargs
    - features_extractor_kwargs:
        aux_obs_dim: 10
        batch_normalization: false
        bn_eps: 1.0e-05
        bn_momentum: 0.01
        channel_multiplier: 32
        channels_in: 7
        depth: 4
        fast_conv: true
        features_dim: 160
        full_depth: 2
        full_depth_channels: 16
        full_depth_conv1d: true
        separate_networks_for_stacks: true
      n_critics: 2
      n_quantiles: 25
      net_arch:
      - 512
      - 512
      separate_networks_for_stacks: true
      share_features_extractor: true
      use_sde: false
  - - target_entropy
    - auto
  - - tau
    - 5.0e-05
  - - top_quantiles_to_drop_per_net
    - 3
  - - train_freq
    - - 1
      - episode
  - - use_sde
    - false
